CREATE TABLE project (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE),
	"name" varchar(50) NOT NULL,
	color varchar(6) NOT NULL,
	CONSTRAINT project_name_1ecf4961_uniq UNIQUE (name),
	CONSTRAINT project_pkey PRIMARY KEY (id)
);
CREATE INDEX project_name_1ecf4961_like ON project USING btree (name varchar_pattern_ops);


---- create above / drop below ----

DROP TABLE project;

