
CREATE TABLE timer (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE),
	start_datetime timestamptz NOT NULL,
	end_datetime timestamptz NULL,
	note varchar(30) NOT NULL,
	project_id int8 NULL,
	duration interval NULL,
	previous_id int8 NULL,
	CONSTRAINT timer_pkey PRIMARY KEY (id),
	CONSTRAINT timer_previous_id_bffcba8d_fk_timer_id FOREIGN KEY (previous_id) REFERENCES timer(id) DEFERRABLE INITIALLY DEFERRED,
	CONSTRAINT timer_project_id_6fbe5b43_fk_project_id FOREIGN KEY (project_id) REFERENCES project(id) DEFERRABLE INITIALLY DEFERRED
);
CREATE INDEX timer_previous_id_bffcba8d ON timer USING btree (previous_id);
CREATE INDEX timer_project_id_6fbe5b43 ON timer USING btree (project_id);

---- create above / drop below ----

DROP TABLE timer;