// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.513
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func Login(err string) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
			if !templ_7745c5c3_IsBuffer {
				templ_7745c5c3_Buffer = templ.GetBuffer()
				defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div><a href=\"/auth\"><svg viewBox=\"0 0 25 25\" style=\"width: 1.5rem;\" xmlns=\"http://www.w3.org/2000/svg\"><path cx=\"512\" cy=\"512\" r=\"512\" style=\"fill:#008aaa\" d=\"M25 12.5a12.5 12.5 0 0 1 -12.5 12.5A12.5 12.5 0 0 1 0 12.5a12.5 12.5 0 0 1 25 0z\"></path> <path d=\"M19.194 9.656h-1.968a0.104 0.104 0 0 1 -0.09 -0.051l-1.58 -2.739a0.107 0.107 0 0 0 -0.092 -0.051H9.018a0.104 0.104 0 0 0 -0.09 0.051L7.285 9.707 5.703 12.446a0.114 0.114 0 0 0 0 0.105l1.583 2.739 1.641 2.844a0.098 0.098 0 0 0 0.09 0.051h6.448c0.037 0 0.073 -0.02 0.092 -0.051l1.583 -2.739a0.098 0.098 0 0 1 0.09 -0.051h1.968a0.117 0.117 0 0 0 0.117 -0.117V9.775a0.122 0.122 0 0 0 -0.12 -0.12zm-7.536 5.74L11.161 16.25a0.107 0.107 0 0 1 -0.033 0.033 0.105 0.105 0 0 1 -0.046 0.013H10.1a0.088 0.088 0 0 1 -0.081 -0.049L8.551 13.7l-0.144 -0.251 -0.527 -0.901a0.07 0.07 0 0 1 -0.01 -0.044c0 -0.015 0.005 -0.033 0.013 -0.044l0.53 -0.917 1.609 -2.782a0.098 0.098 0 0 1 0.081 -0.049h0.981c0.018 0 0.034 0.005 0.051 0.013a0.083 0.083 0 0 1 0.033 0.033l0.496 0.859a0.096 0.096 0 0 1 -0.005 0.092L10.07 12.461a0.08 0.08 0 0 0 -0.01 0.039c0 0.015 0.005 0.027 0.01 0.039l1.589 2.751a0.099 0.099 0 0 1 0 0.107zm4.934 -2.849 -0.527 0.9 -0.144 0.251 -1.467 2.547a0.094 0.094 0 0 1 -0.081 0.049h-0.984a0.101 0.101 0 0 1 -0.046 -0.013 0.083 0.083 0 0 1 -0.033 -0.033l-0.496 -0.854a0.092 0.092 0 0 1 -0.003 -0.103l1.589 -2.751a0.08 0.08 0 0 0 0.01 -0.039 0.098 0.098 0 0 0 -0.01 -0.039L12.813 9.71a0.096 0.096 0 0 1 -0.005 -0.092l0.496 -0.859a0.088 0.088 0 0 1 0.083 -0.044h0.986c0.034 0 0.066 0.018 0.081 0.049l1.609 2.782 0.53 0.917a0.104 0.104 0 0 1 0.013 0.044 0.098 0.098 0 0 1 -0.013 0.039z\" style=\"fill:#fff\"></path></svg> ")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Var3 := `Sign in with Keycloak`
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var3)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</a></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if !templ_7745c5c3_IsBuffer {
				_, templ_7745c5c3_Err = io.Copy(templ_7745c5c3_W, templ_7745c5c3_Buffer)
			}
			return templ_7745c5c3_Err
		})
		templ_7745c5c3_Err = base().Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
